# Generated by Django 3.2.7 on 2021-09-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_snapshotfile_videofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshotfile',
            options={'ordering': ('-reg_date',)},
        ),
        migrations.AlterModelOptions(
            name='videofile',
            options={'ordering': ('-reg_date',)},
        ),
    ]
